### ISSUE TITLE
Get website up and running

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/devxconf.org#11]
After speaking with a few people it would really help to get more credibility if we have a redacted version of the website already live so we can trigger credibility with design/style etc. It would be great to have devxconf.org with the new kumuqat design that only includes landing page & manifesto (no diversity, speaker, community, expo section) up and running by tomorrow. Things that the landing page should not include for now: 

- Speakers 
- Partners
- Twitter 

Potentially we have some "Coming soon" header somewhere.

**Comment by nisarhassan12** [comment]
This is no longer relevant. Please re-open if something needs to be addressed.
