### ISSUE TITLE
Re-add "speaker" in the navigation bar

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/devxconf.org#126]
It'd be great to continue having the speaker overview. Could you re-add the speaker menu to the navigation bar @nisarhassan12 ?

**Comment by nisarhassan12** [comment]
Fixed in https://github.com/gitpod-io/devxconf.org/commit/49e37a0de6544aa7f037ef7449140ea74aca2c54 I had to make the nav items smaller and reduce the spacing between then because there was not enough room and the layout was breaking.
