### ISSUE TITLE
Setup a new GitHub Oauth app for this year

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/devxconf.org#129]
We need to create a new Github Oauth app for this year's conf as the old one will not work for the users who signed up for the conf via GitHub last year as the current DevX Oauth App already exists for them under https://github.com/settings/applications so it shows the `You have already registered.`  Popup

![image](https://user-images.githubusercontent.com/46004116/160834985-aa135b53-10a3-4815-915b-f8e737ff7392.png)

**Comment by mikenikles** [comment]
I no longer have access to the `gitpod-io` org to make this happen. Nisar, please work with [one of the owners](https://github.com/orgs/gitpod-io/people?query=role%3Aowner), they can help with that.

**Comment by nisarhassan12** [comment]
Moritz set up the new GitHub Oauth App and I changed the environment variables in Vercel.
