### ISSUE TITLE
Update speakers 

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/devxconf.org#131]
From Ana:

Change my talk title to “Peer Support: Your distributed debugging machine”
Change my work title to "Devtools UX Researcher"

New submission from [Oleg](https://docs.google.com/forms/d/e/1FAIpQLScj4mKIBL6OhU90usyIw5hF6fZUNtg6TFbKc-D6a4K8Md-cZw/viewform?usp=sf_link) and [Tarun](https://docs.google.com/forms/d/e/1FAIpQLScj4mKIBL6OhU90usyIw5hF6fZUNtg6TFbKc-D6a4K8Md-cZw/viewform?usp=sf_link).

**Comment by pawlean** [comment]
Hi @nisarhassan12! There are a few things I didn't see in your original PR. Can you add? 

FYI: I could do this myself but for some reason, every time I open a Gitpod workspace in this repo, it gives me a generic white-themed Gitpod workspace with no memory of my account despite me being logged in. Have you seen this before? 🤔

**Comment by nisarhassan12** [comment]
> Can you add?

Doing that now. 

> Have you seen this before? 

Yeah. I think I have seen that before maybe twice not sure why is it. Also, the port does not seem to open the preview as well. 

For the Gitpod website repo, it seems to work well and I have never seen this there.

**Comment by nisarhassan12** [comment]
@pawlean I have fixed the setup in https://github.com/gitpod-io/devxconf.org/pull/132 It should now work fine.

**Comment by pawlean** [comment]
> @pawlean I have fixed the setup in #132 It should now work fine.

Star. Thank you!
