### ISSUE TITLE
Add DevX Conf schedule

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/devxconf.org#138]
Once our schedule is finalised[[1](https://www.notion.so/gitpod/create-conference-schedule-495d2a222adb42ae81f30e0ac992be38)], we need to it to the website.

💭 I was looking at last year's design [[2](https://www.figma.com/file/Xsm95RBYugIxOc2bBaVvnF/DevX-Conf?node-id=35%3A1343)] and thought we could adopt a similar layout, apart from it being one video stream with the day schedule on the right-hand side? cc/ @chrifro any thoughts?

❓ Pre-conference, did you also have the schedule anywhere on the website? E.g. the landing page? Is this something we should consider this year?

Also tracking **[here (internal document)](https://www.notion.so/gitpod/Add-DevX-Conf-schedule-to-website-86236648566a49198ea96a4a917e30d0)**

**Comment by chrifro** [comment]
Before the event takes place we can use this layout and add a navigation item for it
<img width="722" alt="Bildschirmfoto 2022-04-04 um 14 22 15" src="https://user-images.githubusercontent.com/46345125/161542677-da73a944-a7ce-4ad3-a89b-06613e175ad8.png">

And afterward the event, we can use this layout. I think it would be best to cut the stream after the event and to create individual videos for each talk. These individual videos can then be linked here (without the discord link):
<img width="719" alt="Bildschirmfoto 2022-04-04 um 14 22 29" src="https://user-images.githubusercontent.com/46345125/161542856-02299ea3-0b5a-411f-b01b-26bb5e8392eb.png">
 
Is that what you had in mind as well @pawlean ?

**Comment by pawlean** [comment]
That is perfect. 🎯 @chrifro 

Let's use the same layout this year. 

How about during the event? I guess we could have the embedded video on the front page?

**Comment by pawlean** [comment]
**Update:** We are still reviewing the schedule but I'd like it up this week. 👀
