### ISSUE TITLE
Small website improvements

### ISSUE THREAD

**Issue by chrifro** [gitpod-io/devxconf.org#139]
- [x] update the date 
<img width="639" alt="Bildschirmfoto 2022-04-04 um 11 56 02" src="https://user-images.githubusercontent.com/46345125/161536922-929ca03f-aea0-42f8-8b86-adba752e1fde.png">

- [x] delete last years sponsors. I don't see any value in listing them
<img width="859" alt="Bildschirmfoto 2022-04-04 um 11 57 08" src="https://user-images.githubusercontent.com/46345125/161537097-430a6ba4-c6fd-40a4-b8ff-0db6d45e0160.png">
alternative layout:
<img width="546" alt="Bildschirmfoto 2022-04-04 um 13 46 48" src="https://user-images.githubusercontent.com/46345125/161537328-2dd8637e-2d2b-4b95-a353-544941c6a247.png">

- [x] the page order of the prospectus is wrong. See order [here](https://www.figma.com/file/Xsm95RBYugIxOc2bBaVvnF/DevX-Conf?node-id=300%3A797)
 

- [x] change navigation order: manifest, open-source funding, community and 2021

Could you look into this @nisarhassan12 ? 🙏

**Comment by nisarhassan12** [comment]
> - [x]  update the date

@chrifro I have updated the 2nd of May.
