### ISSUE TITLE
Server render the individual speaker pages

### ISSUE THREAD

**Issue by nisarhassan12** [gitpod-io/devxconf.org#143]
At the moment the preview for the individual speaker pages says undefined and that is because the pages are not server rendered.

Originated from this [private Slack message](https://gitpod.slack.com/archives/C01LV88Q83S/p1649272475794509?thread_ts=1649272358.663419&cid=C01LV88Q83S)

**Comment by pawlean** [comment]
Hey @nisarhassan12 - any updates on this?

**Comment by nisarhassan12** [comment]
Hey @pawlean I'm busy with a lot of stuff at the moment. I'll try to get this done by the coming Monday.
