### ISSUE TITLE
Add hosts profiles

### ISSUE THREAD

**Issue by pawlean** [gitpod-io/devxconf.org#155]
💡 We should add a section above the "Speakers" section called "Hosts" with the paragraph underneath that says "Your hosts for DevX Conf"

Add a profile for Pauline and Michael.

Makes it feel more like a conference. WDYT?

**Comment by MichaelAring** [comment]
I like the idea and we should definitely do it. I would only suggest that we place the new host section below the speaker section. IMHO the speaker section is much more impactful. We as hosts are not in the foreground (as in we are not the reason someone might attend. A specific speaker may be a reason to attend).

**Comment by pawlean** [comment]
💯  Sounds like a plan. Thanks for the input @MichaelAring 🙏🏼 

@nisarhassan12 We've completed our details [here](https://docs.google.com/spreadsheets/d/1YHMle2t0-qzVvG8H81qdXTBm0haqbILdHCNkrlxvjJ4/edit?usp=sharing). Can you add us on the website?
