### ISSUE TITLE
Vitual Event Starter Kit Preview is still cached

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/devxconf.org#17]
If I bookmark the page it shows the below:

<img width="817" alt="CleanShot 2021-03-17 at 22 07 17@2x" src="https://user-images.githubusercontent.com/22498066/111538804-6e800200-876d-11eb-9e83-00ad4e5c5293.png">

**Comment by nisarhassan12** [comment]
Fixed in https://github.com/gitpod-io/devxconf.org/commit/aa95e5452385e7b29a0670a1938b9ae422d0c7e8
