### ISSUE TITLE
Update primary button style

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/devxconf.org#19]
The primary button should have a black font color, as a white font is a lot harder to read. 

Mockup:
<img width="724" alt="Bildschirmfoto 2021-03-19 um 13 30 49" src="https://user-images.githubusercontent.com/46345125/111780282-78ae1780-88b7-11eb-8522-3937da9b89ea.png">

**Comment by nisarhassan12** [comment]
Fixed in #https://github.com/gitpod-io/devxconf.org/commit/d67e678a74feedd563b84a1fe4806d95076b61c4
