### ISSUE TITLE
Font color on https://devxconf.org/code-of-conduct

### ISSUE THREAD

**Issue by estelle** [gitpod-io/devxconf.org#28]
The rest of the site is --text-white, which is super easy to read, but the paragraphs on the CoC page are --grey. The white is so much easier on the eyes. Can the CoC and footer links be lightened?

while the 5.14 is AA compliant, this dark on dark is hard to read, especially for people with astigmatism.

**Comment by ChristinFrohne** [comment]
Thanks for looking into it @estelle. Sure we can make it lighter. 

Let's have the footer in #8E8787 and make the body text in Code of Conduct and privacy policy white #FDFBFB. 

Could you adjust this @nisarhassan12 ?
