### ISSUE TITLE
Add sponsors

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/devxconf.org#36]
Add sponsors underneath "partners". You can find the sponsor logos in our google drive folder

**Order:** 
CodeSee, Sourcegraph, Raycast, Useoptic, CNCF, Cloudquery

**Comment by nisarhassan12** [comment]
Fixed in https://github.com/gitpod-io/devxconf.org/commit/967d814ad993d1e0f09442df2d26639fb5ace0db
