### ISSUE TITLE
Old Gitpod logo on Community Day

### ISSUE THREAD

**Issue by JohannesLandgraf** [gitpod-io/devxconf.org#87]
<img width="368" alt="CleanShot 2021-04-21 at 09 41 45@2x" src="https://user-images.githubusercontent.com/22498066/115515835-cbe40300-a285-11eb-9ccf-408996882c7f.png">

**Comment by nisarhassan12** [comment]
Fixed in https://github.com/gitpod-io/devxconf.org/commit/3625ffa1c37b406004894aabb3c2c0c165055ce1
