### ISSUE TITLE
Add console.dev as a sponsor

### ISSUE THREAD

**Issue by mikenikles** [gitpod-io/devxconf.org#89]
URL: https://console.dev/?ref=gitpod
Description for the expo page: Console is a free weekly email digest of the best tools and beta releases for developers.
Logo: Please message me, can't attach svg files here.
Screenshot: 
![console-homepage](https://user-images.githubusercontent.com/788827/115583301-c4c5f080-a297-11eb-9e2e-a0c56805dedf.jpeg)

**Comment by nisarhassan12** [comment]
Thanks, @mikenikles What is gonna be the tier for it? i.e `gold`, `silver` or `start-up` ?

**Comment by mikenikles** [comment]
@ghuntley could you answer the Discord invite link question? I created a channel, but noticed it doesn't have the Zapier integration configured like the other sponsors. It'd be awesome if you could point me to instructions on how to set up a new sponsor or run with it 🙏 .

**Comment by ChristinFrohne** [comment]
Here is the discord link to their channel: https://discord.gg/srE7fVe3gC

You can list them as a Silver sponsor  @nisarhassan12
