### ISSUE TITLE
[on hold until he confirms his speaker slot] Add Micha as a speaker 

### ISSUE THREAD

**Issue by ChristinFrohne** [gitpod-io/devxconf.org#96]
Name: Micha Hernandez van Leuffen

Title: "operating intelligence in a cloud-native environment"

https://www.linkedin.com/in/mhernandezvanleuffen/
https://twitter.com/mies

![mies](https://user-images.githubusercontent.com/46345125/115668316-41fc6e80-a347-11eb-8f52-d595e4c0b1ba.jpeg)

**Comment by nisarhassan12** [comment]
Closing this as it's confirmed that he is not gonna be a speaker.
